import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  forceCenter,
  forceCollide,
  forceLink,
  forceManyBody,
  forceRadial,
  forceSimulation,
  forceX,
  forceY,
} from "d3-force";
import { buildGraph } from "../src/data/build";
import {
  ALPHA_DECAY,
  DEFAULT_SIM_FORCES,
  RADIAL_RADIUS,
  RADIAL_STRENGTH,
  VELOCITY_DECAY,
  chargeStrength,
  centerStrength,
  collideRadius,
  linkDistance,
  linkStrength,
} from "../src/lib/forceParams";

interface SimNode {
  id: string;
  size: number;
  x: number;
  y: number;
}

interface SimLink {
  source: string | SimNode;
  target: string | SimNode;
  kind: "tree" | "cross";
}

const TICKS = 900;

const built = buildGraph();
const forces = DEFAULT_SIM_FORCES;

const simNodes: SimNode[] = built.nodes.map((n) => ({
  id: n.id,
  size: n.size,
  x: n.x,
  y: n.y,
}));

const links: SimLink[] = built.edges.map((e) => ({
  source: e.source,
  target: e.target,
  kind: e.kind,
}));

const sim = forceSimulation(simNodes)
  .force(
    "link",
    forceLink<SimNode, SimLink>(links)
      .id((d) => d.id)
      .distance((l) => linkDistance(forces.distance, l.kind))
      .strength((l) => linkStrength(forces.link, l.kind)),
  )
  .force(
    "charge",
    forceManyBody<SimNode>()
      .strength(chargeStrength(forces.repel))
      .distanceMax(700),
  )
  .force("center", forceCenter(0, 0))
  .force("x", forceX<SimNode>(0).strength(centerStrength(forces.center)))
  .force("y", forceY<SimNode>(0).strength(centerStrength(forces.center)))
  .force(
    "radial",
    forceRadial<SimNode>(RADIAL_RADIUS, 0, 0).strength(RADIAL_STRENGTH),
  )
  .force("collide", forceCollide<SimNode>((d) => collideRadius(d.size)).iterations(2))
  .alphaDecay(ALPHA_DECAY)
  .velocityDecay(VELOCITY_DECAY)
  .stop();

for (let i = 0; i < TICKS; i++) sim.tick();

let minX = Infinity;
let maxX = -Infinity;
let minY = Infinity;
let maxY = -Infinity;
for (const n of simNodes) {
  minX = Math.min(minX, n.x);
  maxX = Math.max(maxX, n.x);
  minY = Math.min(minY, n.y);
  maxY = Math.max(maxY, n.y);
}

const round = (v: number) => Math.round(v * 10) / 10;
const entries = simNodes
  .map((n) => `  ${JSON.stringify(n.id)}: [${round(n.x)}, ${round(n.y)}],`)
  .join("\n");

const out = `// AUTO-GENERATED by scripts/precompute-layout.ts - do not edit by hand.
// Deterministic settled layout (d3-force, Obsidian-style forces) baked at build time
// so the graph renders instantly, stays on screen, and needs no runtime simulation.
// ${simNodes.length} nodes · ${TICKS} ticks · bbox ${Math.round(maxX - minX)}×${Math.round(maxY - minY)}

export const LAYOUT: Record<string, [number, number]> = {
${entries}
};
`;

const target = join(process.cwd(), "src", "data", "layout.ts");
writeFileSync(target, out);
console.log(
  `wrote ${target}: ${simNodes.length} nodes, bbox ${Math.round(maxX - minX)}x${Math.round(maxY - minY)}, alpha=${sim.alpha().toExponential(2)}`,
);
