#!/usr/bin/env python
"""Emit graph/src/data/modules/evidence.ts from the E branch of index.html's DATA.

Keeps the tree (index.html) and the graph (Next.js app) carrying identical
transcript evidence without hand-maintaining two copies.
"""
import json, re
from pathlib import Path

ROOT = Path.home() / "Documents/Projects/hormozi-brain-tree"
IDX = ROOT / "index.html"
OUT = ROOT / "graph/src/data/modules/evidence.ts"

src = IDX.read_text()
m = re.search(r"const DATA\s*=\s*", src)
start = m.end()
depth, i, instr, esc = 0, start, False, False
while i < len(src):
    c = src[i]
    if instr:
        if esc: esc = False
        elif c == "\\": esc = True
        elif c == '"': instr = False
    else:
        if c == '"': instr = True
        elif c == "{": depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0: break
    i += 1
DATA = json.loads(src[start:i + 1])

E = next(c for c in DATA["children"] if c["id"] == "E")

def ts(s):
    """TS string literal, safely escaped."""
    return json.dumps(s, ensure_ascii=False)

def emit(node, indent=2, is_root=False):
    pad = " " * indent
    kind = node.get("kind", "rule")
    if kind == "branch": kind = "module"      # graph NodeType has no "branch"
    # DSL convention: child ids are relative to their parent, so the module id
    # must match ModuleId ("evidence") and descendants use the last segment only.
    nid = "evidence" if is_root else node["id"].split(".")[-1]
    fields = []
    fields.append(f"type: {ts(kind)}")
    if node.get("spec"): fields.append(f"summary: {ts(node['spec'])}")
    if node.get("detail"): fields.append(f"detail: {ts(node['detail'])}")
    if node.get("quotes"):
        qs = ", ".join(
            "{ t: %s, src: %s, vid: %s }" % (ts(q["t"]), ts(q["src"]), ts(q["vid"]))
            for q in node["quotes"]
        )
        fields.append(f"quotes: [{qs}]")
    kids = node.get("children", [])
    if kids:
        body = ",\n".join(emit(k, indent + 2) for k in kids)
        fields.append(f"children: [\n{body},\n{pad}]")
    inner = (",\n" + pad + "  ").join(fields)
    return f"{pad}n({ts(nid)}, {ts(node['title'])}, {{\n{pad}  {inner},\n{pad}}})"

lines = [
    "// AUTO-GENERATED by scripts/gen-evidence-module.py - do not edit by hand.",
    "// Source: the E branch of index.html, mined from 516 channel transcripts.",
    'import { n } from "../dsl";',
    "",
    f"export const evidence = {emit(E, 0, is_root=True)};",
    "",
]
OUT.write_text("\n".join(lines))
print("wrote", OUT, OUT.stat().st_size, "bytes")

def count(n_):
    return 1 + sum(count(c) for c in n_.get("children", []))
print("evidence nodes:", count(E))
