// AUTO-GENERATED by scripts/gen-evidence-module.py - do not edit by hand.
// Source: the E branch of index.html, mined from 516 channel transcripts.
import { n } from "../dsl";

export const evidence = n("evidence", "Evidence & Benchmarks - what the transcripts add", {
  type: "module",
  summary: "The numbers behind the frameworks, mined from 516 transcripts of the channel. Every node carries a verbatim quote and its source video.",
  children: [
  n("1", "The corpus itself", {
    type: "framework",
    summary: "516 of 523 videos transcribed - 2.9M words, 219 hours. Every quote in this branch is traceable to a video.",
    detail: "This branch is built from a full pass over the channel: **523 videos listed, 516 transcribed** (2.9M words / 219 hours of video; 7 have captions disabled). Quotes are verbatim from auto-generated captions, so expect occasional transcription noise in the wording - the numbers are reliable, the punctuation is not.\n\nMethod: transcripts pulled with yt-dlp, sentence-mined for teachable passages carrying a number, mechanism, or polarity claim, then filtered against promo language. The frameworks elsewhere in this tree came from the written sources; this branch is what the spoken material adds on top - mostly **benchmarks, ratios, and thresholds** that the books state as principles but rarely quantify.\n\nProvenance for every quote: `sources/quotes.json` in this repo, keyed by video ID, with the full transcript corpus.",
    children: [
    n("1", "523 videos, 516 transcribed", {
      type: "rule",
      summary: "2.9M words. 7 videos have captions disabled by the channel.",
    }),
    n("2", "Quote provenance", {
      type: "rule",
      summary: "Every quote carries title + video ID. Full index in sources/quotes.json.",
    }),
    n("3", "What the transcripts add", {
      type: "rule",
      summary: "Benchmarks, ratios and thresholds - the numbers the written frameworks leave qualitative.",
    }),
  ],
  }),
  n("2", "Pricing by close rate", {
    type: "framework",
    summary: "The single most actionable instrument in the corpus: your close rate tells you exactly how mispriced you are.",
    detail: "From **The Mathematics of Business, Explained** - Hormozi's close-rate-to-price ladder, described as a rule of thumb collected over years of business:\n\n| Close rate | Verdict | Move on a $100 price |\n|---|---|---|\n| **80%+** | underpriced 3-4x | charge $300-400 |\n| **50-60%** | underpriced 1.5-2x | charge $150-200 |\n| **40-50%** | underpriced 1.25-1.5x | charge $125-150 |\n| **30-40%** | appropriately priced | hold |\n| **<25%** | too expensive / broken | fix the process, not the price |\n\nThe insight that makes it work: a *high* close rate is expensive. Closing four out of five people means you left margin on every one of those deals, and the fix is a price rise, not a victory lap. The jumps compress as you approach the target zone - the further you are from 35%, the bigger the correction.\n\nThe 30-40% band is only 'correct' **conditional on having the mechanisms in place to educate the buyer before the pitch** - proof, pre-selling, content. Without those, the same close rate means something else.",
    children: [
    n("1", "80%+ close → underpriced 3-4x", {
      type: "rule",
      summary: "Four out of five buying means 3-4x left on the table.",
      detail: "**Quote:** 'If you're closing at 80% or more in whatever you sell, so four out of five people you talk to buy your thing, you're typically underpriced by 3 to 4x. That might sound mindblowing to you, but that is just the data that I've, again, rule of thumb that I've collected over many years of business.'",
      quotes: [{ t: "If you're closing at 80% or more in whatever you sell, so four out of five people you talk to buy your thing, you're typically underpriced by 3 to 4x.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("2", "50-60% close → underpriced 1.5-2x", {
      type: "rule",
      summary: "$100 should probably be $150-200.",
      detail: "**Quote:** 'If you're between 50 and 60%, typically you're underpriced by one and a half to 2x. So that $100 price point should probably be one and a half. So $150 or $200.'",
      quotes: [{ t: "If you're between 50 and 60%, typically you're underpriced by one and a half to 2x. So that $100 price point should probably be one and a half. So $150 or $200.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("3", "40-50% close → underpriced 1.25-1.5x", {
      type: "rule",
      summary: "$100 should probably be $125-150.",
      detail: "**Quote:** 'Now if you're between 40 and 50% close rates, you're probably between 1.25 to 1.5x underpriced. Meaning now you should be at maybe 125 or consider 150 as a final price point.'",
      quotes: [{ t: "Now if you're between 40 and 50% close rates, you're probably between 1.25 to 1.5x underpriced. Meaning now you should be at maybe 125 or consider 150 as a final price point.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("4", "30-40% close → appropriately priced", {
      type: "rule",
      summary: "The target band - conditional on pre-pitch education mechanisms.",
      detail: "**Quote:** 'If you have that sales motion and you were closing 35%, you're appropriately priced - under the assumption you have all of the selling mechanisms in place to educate a consumer prior to the purchase so that you're not creating a pitch or a spiel. Instead, they've already consumed all of this stuff prior to the pitch and then the entire close call is about personalization.'",
      quotes: [{ t: "If you have that sales motion and you were closing 35%, you're appropriately priced under the assumption you have all of the selling mechanisms in place to educate a consumer prior to the purchase.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("5", "<25% close → fix the process first", {
      type: "rule",
      summary: "Never cut price as the opening move.",
      detail: "**Quote:** 'If somebody's closing, let's say, 25% or less, they get bumped down.' And on the general principle: 'If it's below that, then I will fix the process before I even consider lowering the price.'\n\nPrice is the last lever. A low close rate is evidence of a broken mechanism - weak proof, no pre-selling, a pitch instead of an education - before it is evidence of a high price.",
    }),
  ],
  }),
  n("3", "Retention is the highest-leverage number", {
    type: "framework",
    summary: "LTV = annual payment ÷ churn rate. A 30-point retention gain multiplies customer value 2.5x.",
    detail: "**LTV = annual payment ÷ churn rate.**\n\n| Annual retention | LTV on $100/year |\n|---|---|\n| 50% | $200 (÷ 0.5) |\n| 80% | $500 (÷ 0.2) |\n\nA move from 50% to 80% retention looks like a 30-point improvement. In LTV terms it is **2.5x more value from the same customer** - which is why retention beats acquisition on leverage, and why 'raise your prices, decrease churn' is the whole recipe for making customers worth more.\n\nThe corollary on growth: model new inflow against churn before celebrating it. Growing to 300 members at 10% churn means a large slice of acquisition spend is replacing outflow rather than expanding the base.",
    children: [
    n("1", "LTV = annual payment ÷ churn", {
      type: "rule",
      summary: "The core retention formula, stated plainly.",
      detail: "**Quote:** 'You can take whatever your annual retention is and then you can basically reverse engineer into what your lifetime value of a customer is. So, if you have 50% annual retention, then you can take whatever someone pays over a year, let's use simple math and say someone pays $100 per year. If you have 50% annual retention, then it means that you can basically double it. So, you divide it by 50%. equals $200 is what you're going to make from a customer.'",
      quotes: [{ t: "If you have 50% annual retention, then you can take whatever someone pays over a year - say $100 - and it means that you can basically double it. You divide it by 50%, equals $200 is what you're going to make from a customer.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("2", "80% retention → 5x, not 2x", {
      type: "rule",
      summary: "A 30-point gain is a 2.5x value gain. This is the punchline.",
      detail: "**Quote:** 'Let's say that you have 80% annual retention. Doesn't seem like that much different, right? It's only 30%. What is it actually different from a math perspective? It means that you're going to get functionally four turns, five turns because every year you're going to lose 20%. And so simple math on that, back of napkin, is about $500.'",
      quotes: [{ t: "Let's say that you have 80% annual retention. Doesn't seem like that much different, right? It's only 30%. It means that you're going to get functionally four turns, five turns because every year you're going to lose 20%.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("3", "Inflow vs churn", {
      type: "rule",
      summary: "300 members at 10% churn - most new inflow replaces outflow.",
      detail: "**Quote:** 'If you want to grow to let's say 300 members, and let's say your churn is 10%.' Growth math has to net churn off the top before any of it counts as growth.",
      quotes: [{ t: "If you want to grow to let's say 300 members, and let's say your churn is 10%.", src: "Your Inflow Is Your Bottleneck", vid: "XC_lklN9KmE" }],
    }),
  ],
  }),
  n("4", "LTV:CAC - floor vs arbitrage", {
    type: "framework",
    summary: "3:1 keeps you alive. 30:1+ makes you rich. Gym Launch year one ran 100:1.",
    detail: "The 3:1 LTV:CAC ratio is the traditional software-world rule of thumb, widely circulated and widely adopted. It is a **durability floor**, not an ambition.\n\nHormozi's outsized returns came from short windows where a channel was mispriced against customer value:\n\n- **Gym Launch, year one: 100:1.** 'I spent a hundred grand and made 10 million.'\n- **Four windows in his life, every one above 30:1.**\n\n'Most of the money that I've made in my life has happened during these distinct windows of opportunity where there was huge arbitrage between what it cost me to get a customer and what a customer is worth to me.'\n\nThe operating instruction that follows: keep beating on the money model until you land in a window, then scale spend hard and **do not cap it**. He states he never caps launch ad spend while the ads are performing. When the window closes, the 3:1 floor is what keeps the business alive.",
    children: [
    n("1", "Gym Launch year one: 100:1", {
      type: "rule",
      summary: "$100k spent, $10M made.",
      detail: "**Quote:** 'The first year of gym launch, my LTV CAC was 100 to one. I spent a hundred grand and made 10 million. Wild recommend. It was wild, wild times.'",
      quotes: [{ t: "The first year of gym launch, my LTV CAC was 100 to one. I spent a hundred grand and made 10 million.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("2", "Four windows, all above 30:1", {
      type: "rule",
      summary: "Wealth came from arbitrage windows, not steady-state margins.",
      detail: "**Quote:** 'Most of the money that I've made in my life has happened during these distinct windows of opportunity where there was huge arbitrage between what it cost me to get a customer and what a customer is worth to me. And I've had that happen four times in my life. And each of those times have been above 30 to1. And so the reason I'm so adamant about this is that I know because I've had it happen that you have to just keep beating up the system. You have to keep tweaking the money model.'",
      quotes: [{ t: "Most of the money that I've made in my life has happened during these distinct windows of opportunity where there was huge arbitrage between what it cost me to get a customer and what a customer is worth to me. I've had that happen four times in my life. And each of those times have been above 30 to1.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("3", "Don't cap spend inside a window", {
      type: "rule",
      summary: "He never caps launch ad spend while ads are performing.",
      detail: "**Quote:** 'I never go into my launch capping my total ad spend if the ads are performing as I want them to.' A live arbitrage window is the one time to scale spend aggressively.",
      quotes: [{ t: "I never go into my launch capping my total ad spend if the ads are performing as I want them to.", src: "Building a $3,000,000 Business for a Stranger in 31 Minutes", vid: "j2TZMFkj71Q" }],
    }),
    n("4", "30-day CAC payback target", {
      type: "rule",
      summary: "Recover CAC inside 30 days - the interest-free float on a credit card.",
      detail: "**Quote:** 'My goal is within 30 days. Why? Because just about every business owner can typically gain access to a credit card which gives you 30 days of interest free money.' Payback inside 30 days means acquisition is effectively self-funding.",
    }),
  ],
  }),
  n("5", "Sales benchmarks", {
    type: "framework",
    summary: "35% close = quota. 70% calendar utilisation = sweet spot. Above quota → raise price.",
    detail: "The numbers that grade a sales function:\n\n- **35% close rate** - a rep should close at least one in three touched prospects. Above that, he raises price; below, he fixes the process.\n- **25% or less** - the rep gets bumped down a tier.\n- **70% calendar utilisation** - the sweet spot for booked sales capacity.\n\nOn utilisation, both extremes are bad. A fully-booked team makes more sales but **conversion drops and CAC rises**, because leads wait longer and book further out. Under-utilised is wasted payroll. 70% is the target that keeps conversion healthy while keeping reps busy.",
    children: [
    n("1", "35% close = rep quota", {
      type: "rule",
      summary: "One in three touched prospects.",
      detail: "**Quote:** 'My rule of thumb with sales people in general with a proper sales process is 35%. I would like them to close at least one out of three of the prospects that they're getting touched with. Typically, if it's higher than that, I will raise price. And if it's below that, then I will fix the process before I even consider lowering the price.'",
      quotes: [{ t: "My rule of thumb with sales people in general with a proper sales process is 35%. I would like them to close at least one out of three of the prospects that they're getting touched with.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("2", "Above quota → raise price", {
      type: "rule",
      summary: "A rep closing better than 35% is evidence the price is low.",
      detail: "**Quote:** 'If it's higher than that, I will raise price.' The rep's close rate and the product's price are read off the same instrument - see the close-rate ladder (E.2).",
    }),
    n("3", "70% calendar utilisation", {
      type: "rule",
      summary: "Fully booked is not the goal - conversion falls and CAC rises.",
      detail: "**Quote:** 'Rule number five. 70% calendar utilization. So when you have more salespeople, there's another issue that starts to come up, which is my sales team's underutilized or they're booked out. So what's the sweet spot? If you have your sales team completely booked out, here's two things that happen that are bad. Number one is that your total lead conversion will go down. You will make more sales because they're booked out for sure, but your conversion rates will go down, meaning your CAC, your cost to acquire customers will go up.'",
    }),
    n("4", "<25% → bump the rep down", {
      type: "rule",
      summary: "Below-quota reps move down a tier rather than getting a price cut.",
      detail: "**Quote:** 'If somebody's closing, let's say, 25% or less, they get bumped down.'",
      quotes: [{ t: "If somebody's closing, let's say, 25% or less, they get bumped down.", src: "How I Scaled My Sales Team", vid: "okA9Yt2KZuk" }],
    }),
  ],
  }),
  n("6", "Tiering and the demand fractal", {
    type: "framework",
    summary: "5-10x price per tier, ~20% take, each tier must double revenue. The top 20% outspend the bottom 80%.",
    detail: "The pricing structure that follows from the Pareto distribution of spending power. The top 20% of customers hold far more purchasing power than the 80% beneath them, so price to the top and let the base buy the entry tier.\n\n- **Each new tier: 5-10x the price.**\n- **Expect ~20% to take it.**\n- **Each tier must roughly double total revenue** - 'another full amount of revenue' - or the operational constraint it adds is not worth it.\n\nWorked example, verbatim: 8 customers at $10/month = $80. Add 2 customers at $50/month = $100. The top two customers now out-earn the bottom eight, and total revenue has doubled - from serving the same ten people differently.\n\nThis is why tiering beats discounting. It extracts willingness-to-pay already present in the base instead of lowering the price for everyone.",
    children: [
    n("1", "5-10x price per tier, ~20% take", {
      type: "rule",
      summary: "Big jumps, priced to the top quintile.",
      detail: "**Quote:** 'My rule of thumb is that for every new tier you want to 5 to 10x your price and expect 20% of people to take it.'",
      quotes: [{ t: "My rule of thumb is that for every new tier you want to 5 to 10x your price and expect 20% of people to take it.", src: "Why you aren't making as much money as you want", vid: "ZuJryiwxjDw" }],
    }),
    n("2", "Each tier must double revenue", {
      type: "rule",
      summary: "Otherwise the operational constraint isn't worth it.",
      detail: "**Quote:** 'I want each tier to bring me another double, like another full amount of revenue. Otherwise, I'm like, I don't know if it's worth creating the actual extra constraint of operations.'",
      quotes: [{ t: "I want each tier to bring me another double, like another full amount of revenue. Otherwise, I don't know if it's worth creating the actual extra constraint of operations.", src: "Why you aren't making as much money as you want", vid: "ZuJryiwxjDw" }],
    }),
    n("3", "The 8 x $10 + 2 x $50 example", {
      type: "rule",
      summary: "Top 20% outearn the bottom 80%: $100 vs $80.",
      detail: "**Quote:** 'If you have eight of these customers at $10 per month and you've got two of them at $50 per month, how much am I making? I'm making $80 per month in total on the bottom 80 and then I'm making $100 per month on my top 20%. And so, by serving these two customers differently, we double the revenue of the business.'",
      quotes: [{ t: "If you have eight of these customers at $10 per month and you've got two of them at $50 per month, I'm making $80 per month in total on the bottom 80 and then I'm making $100 per month on my top 20%. By serving these two customers differently, we double the revenue of the business.", src: "Why you aren't making as much money as you want", vid: "ZuJryiwxjDw" }],
    }),
    n("4", "20% of buyers hold the spending power", {
      type: "rule",
      summary: "The Pareto read that makes tiering work.",
      detail: "**Quote:** 'Here's my rule of thumb for upsells taking into account that 20% of customers have far more spending power than the ones below.'",
      quotes: [{ t: "Here's my rule of thumb for upsells taking into account that 20% of customers have far more spending power than the ones below.", src: "Why you aren't making as much money as you want", vid: "ZuJryiwxjDw" }],
    }),
  ],
  }),
  n("7", "Upsell and downsell uptake", {
    type: "framework",
    summary: "20-30% uptake is normal. Assume-close lifts it past 90%. Prefer zero-cost, zero-work upsells.",
    detail: "- **20-30% uptake** is the normal range for a straightforward upsell.\n- **90%+ take rates** are achievable with an *assume close* - presenting the next purchase as already decided rather than asking if they want it.\n- **Zero cost, zero work** upsells are preferred: incremental revenue with no added fulfilment burden.\n\nThe assume-close works because it exploits a pre-programmed response: people are so conditioned to try not to buy things that they end up agreeing when the question is never framed as a yes/no.",
    children: [
    n("1", "20-30% = normal uptake", {
      type: "rule",
      summary: "The baseline for a standard upsell.",
      detail: "**Quote:** 'Most people get 20 to 30% uptake on their upsells. If you use an assume close tactic like this, you can literally see 90% plus take rates on this.'",
      quotes: [{ t: "Most people get 20 to 30% uptake on their upsells. If you use an assume close tactic like this, you can literally see 90% plus take rates.", src: "How To Close Everyone Downselling Like A Pro", vid: "j1tA4l7R2c0" }],
    }),
    n("2", "Zero cost, zero work", {
      type: "rule",
      summary: "Best upsell adds revenue without adding fulfilment.",
      detail: "**Quote:** 'If you have upsells, try and have them be zero cost, zero work upsells, so that you can just make more money up front.'",
      quotes: [{ t: "If you have upsells, try and have them be zero cost, zero work upsells, so that you can just make more money up front.", src: "How to Start a Business From Nothing (Thank Me Later)", vid: "unshZobTt6Q" }],
    }),
    n("3", "Anchor with a top continuity tier", {
      type: "rule",
      summary: "A high tier makes the existing price look reasonable.",
      detail: "**Quote:** 'The first thing we did is we introduced a highest tier continuity option that would make the existing $2,000 a month or $4,500 per quarter seem reasonable by comparison.'",
      quotes: [{ t: "The first thing we did is we introduced a highest tier continuity option that would make the existing $2,000 a month or $4,500 per quarter seem reasonable by comparison.", src: "I Blew Up A Secret Business To Prove It's Not Luck", vid: "SmiOK8Yun4s" }],
    }),
  ],
  }),
  n("8", "Funnel conversion benchmarks", {
    type: "framework",
    summary: "Every added step loses ~50%. Web pages 1-2%. Trusted platform page ~4%. Niche opt-in up to 5% of leads.",
    detail: "The decay numbers that decide how many steps a funnel can afford:\n\n- **Every added step loses about 50% or more.** Two landing pages in a row is not one funnel; it is two 50% haircuts.\n- **Web pages typically convert 1-2%.**\n- **A strong, trusted platform page converts around 4%** - platform trust lifts overall conversion.\n- **Niche opt-in leads convert up to 5% of leads** (leads, not shows).\n\nDesign implication: collapse steps before rewriting copy. Removing a single interstitial page is usually worth more than any headline test, and speed-to-lead compounds the same way.\n\nA real multi-step funnel, for scale: **511 challenge attendees → 26 show up to live sessions daily → 12 sales calls booked → 10 held → 6 closed.**",
    children: [
    n("1", "Each added step ≈ -50%", {
      type: "rule",
      summary: "Two pages in a row means two haircuts.",
      detail: "**Quote:** 'Typically you'll lose about 50%. By like half. Just for every step you add, it's usually about half or more that you lose.'",
      quotes: [{ t: "Typically you'll lose about 50%. By like half. Just for every step you add, it's usually about half or more that you lose.", src: "Building a $2,500,000 Business for a Stranger in 36 Minutes", vid: "OQf2Ba-Lp_4" }],
    }),
    n("2", "Web pages 1-2%, trusted platform ~4%", {
      type: "rule",
      summary: "Trust in the platform raises overall conversion.",
      detail: "**Quote:** 'Web pages, most times it's going to be between 1 and 2% in terms of conversion rate on those pages. I'll give you a fun factoid for School. So I think School right now is at like 4%. It's really good for School about pages and it's because when you have trust in a platform that starts to increase your conversion overall.'",
    }),
    n("3", "Niche opt-in → up to 5% of leads", {
      type: "rule",
      summary: "Tighter niche lifts lead conversion.",
      detail: "**Quote:** 'If you are a little bit more niched, then that can go up to 5% of leads. And like again, that's leads, not shows, right? That's just overall like you had 100 people opt in for webinar.'",
      quotes: [{ t: "If you are a little bit more niched, then that can go up to 5% of leads. That's leads, not shows.", src: "The Mathematics of Business, Explained", vid: "A_tx40lNpf8" }],
    }),
    n("4", "Full funnel benchmark: 511 → 6", {
      type: "rule",
      summary: "511 attendees → 26 show daily → 12 booked → 10 held → 6 closed.",
      detail: "**Quote:** 'The average challenge attendees are 26. So 26 out of the 511 will actually show up to the live sessions each day. Out of that we will typically book 12 sales calls, we'll hold 10 and we'll close six sales.' A useful end-to-end shape for a high-touch funnel.",
      quotes: [{ t: "The average challenge attendees are 26. So 26 out of the 511 will actually show up to the live sessions each day. Out of that we will typically book 12 sales calls, we'll hold 10 and we'll close six sales.", src: "If I Wanted To Scale A Service Business In 2026", vid: "N5MExtki_VI" }],
    }),
  ],
  }),
  n("9", "Volume, focus and the long game", {
    type: "framework",
    summary: "10-30x the volume, not 10%. Consistency only looks impressive at the end.",
    detail: "**Volume:** 'You need to do 10 or 20 or 30 times the volume.' Not 10% more. The distance between where you are and where you want to be is usually a volume gap, and it is almost always larger than it feels from the inside.\n\n**Consistency:** 'The reason so few people understand success is consistency never looks impressive in the moment, only at the end.' The work looks unremarkable while it compounds - which is precisely why most people stop before it does.\n\n**Focus:** 'If you say no, hypothetically, to literally everything except for one thing, you would define that person as incredibly focused, probably obsessive.' Focus is subtraction, and it is defined by what you refuse.\n\n**Wealth:** 'It's better to focus on how to 10x your income than save an additional 10%.' Optimise the numerator, not the denominator.",
    children: [
    n("1", "10-30x the volume", {
      type: "rule",
      summary: "The gap is usually a volume gap, and bigger than it feels.",
      detail: "**Quote:** 'You need to do 10 or 20 or 30 times the volume.'",
      quotes: [{ t: "You need to do 10 or 20 or 30 times the volume.", src: "If You're in Your 20s or 30s, Here's How to Win (at Anything)", vid: "0lMn_-EXyhQ" }],
    }),
    n("2", "Consistency only looks impressive at the end", {
      type: "rule",
      summary: "The middle looks unremarkable, which is why people quit.",
      detail: "**Quote:** 'The reason so few people understand success is consistency never looks impressive in the moment, only at the end.'",
      quotes: [{ t: "The reason so few people understand success is consistency never looks impressive in the moment, only at the end.", src: "Stop Caring What Others Think of You So Much", vid: "qqjGxVW-Ae0" }],
    }),
    n("3", "Focus is subtraction", {
      type: "rule",
      summary: "Say no to everything except one thing.",
      detail: "**Quote:** 'If you say no, hypothetically, to literally everything except for one thing, you would define that person as incredibly focused, probably obsessive.'",
      quotes: [{ t: "If you say no, hypothetically, to literally everything except for one thing, you would define that person as incredibly focused, probably obsessive.", src: "How To Scale Yourself: The What-Why-How Framework", vid: "lIC8fYbrkII" }],
    }),
    n("4", "10x income, not 10% savings", {
      type: "rule",
      summary: "Optimise the numerator.",
      detail: "**Quote:** 'The truth is, it's better to focus on how to 10x your income than save an additional 10%.'",
      quotes: [{ t: "The truth is, it's better to focus on how to 10x your income than save an additional 10%.", src: "Dangerously Honest Advice to Create Generational Wealth", vid: "m-k0_pQJ1fY" }],
    }),
  ],
  }),
],
});
